version: '3'

services:
  blog-back:
    image: node:10    
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app      
    environment:
      ENVIRONMENT: development
      PORT: 3000      
      DB_HOST: mysql
      DB_USER: blog
      DB_PASSWORD: blog
      DB_PORT: 3306
      DB_DATABASE: blog
      JWT_SECRET_KEY: wF9Hpi6vrtQohahz4tIr7h7BKnCasryxmxNXZUW5uaqj9Uq99H
    command:
      - /bin/bash
      - -c
      - |
        pwd 
        npm install
        npm start
  mysql:   
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ../mysql2:/var/lib/mysql
    ports:
      - "3306:3306"   
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
      TZ: Asia/Seoul